### ISSUE TITLE
Cache issues on first run

### ISSUE THREAD

**Issue by eno812** [topdown/VVV-Dashboard#36]
I get the following errors on the first run of the dashboard after install. 

(The permissions on the /cache directory are: drwxr-xr-x)

or directory in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

Warning: scandir(): (errno 2): No such file or directory in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

Warning: Invalid argument supplied for foreach() in /srv/www/default/dashboard/vvv_dash/cache.php on line 167

Warning: scandir(cache/): failed to open dir: No such file or directory in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

Warning: scandir(): (errno 2): No such file or directory in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

Warning: Invalid argument supplied for foreach() in /srv/www/default/dashboard/vvv_dash/cache.php on line 167

Warning: file_put_contents(cache/host-sites-1465186688.txt): failed to open stream: No such file or directory in /srv/www/default/dashboard/vvv_dash/cache.php on line 87

[06-Jun-2016 04:18:08 UTC] PHP Warning: file_put_contents(cache/host-sites-1465186688.txt): failed to open stream: No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 87

[06-Jun-2016 04:18:08 UTC] PHP Warning: Invalid argument supplied for foreach() 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 167

[06-Jun-2016 04:18:08 UTC] PHP Warning: scandir(): (errno 2): No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

[06-Jun-2016 04:18:08 UTC] PHP Warning: scandir(cache/): failed to open dir: No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

[06-Jun-2016 04:18:07 UTC] PHP Warning: Invalid argument supplied for foreach() 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 167

[06-Jun-2016 04:18:07 UTC] PHP Warning: scandir(): (errno 2): No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

[06-Jun-2016 04:18:07 UTC] PHP Warning: scandir(cache/): failed to open dir: No such file or directory 
in /srv/www/default/dashboard/vvv_dash/cache.php on line 165

**Comment by topdown** [comment]
Make sure the directory /srv/www/default/dashboard/cache exists 
And 
`chmod 777 /srv/www/default/dashboard/cache`

**Comment by eno812** [comment]
I'm fairly new to the command line and vagrant. 

Did I need to ssh into vagrant to clone the dashboard first? When I ssh into vagrant and ls, all I get is bin and package xml.

The folder structure exists /www/default/dashboard/cache exists if I exit out of the server. I'm assuming /srv/ is the server not a directory. Sorry for the nube questions.

**Comment by topdown** [comment]
No, you did not need to clone from within vagrant.

I just wanted you to chmod from within vagrant because then I know it would have to permissions needed, since its the vagrant box's PHP that is writing files in the cache folder.

Yes, in this vagrant server setup all site files in the server are under `/srv/www/`

No worries, everyone need to learn starting somewhere.
I'll do what ever I can to help.

**Comment by eno812** [comment]
Thanks for your understanding. 

So once I ssh into vagrant I add the following:
chmod 777 /srv/www/default/dashboard/cache

Or without the /srv/ like this:
chmod 777 /www/default/dashboard/cache

Little confused by the /srv/ as there is no directory called this.

**Comment by topdown** [comment]
:)  Yeah, you don't see it in your file structure, but its there on the server.
I'll show you;

Once you are in vagrant IE `vagrant ssh`
Type `cd /`
That should bring you to the root of the machine (server instance)
Heads up the following `ls` command is `l` as in left `s` as in sam, that can be confused with 1 or I when reading here.
Then type `ls`
You should see an output like 
```
bin   build  etc   initrd.img  lib64       media  opt   root  sbin  sys  usr      var
boot  dev    home  lib         lost+found  mnt    proc  run   srv   tmp  vagrant  vmlinuz
```
See the srv in there.
So if you `cd srv`
then type `ls` again you will see the www folder

So when I say to run
`chmod 777 /srv/www/default/dashboard/cache`

The / slash in the beginning before srv is important because that starts from the root of the system.
Without the starting foreward slash it would start from what ever directory you are in at the time you run the command.

So after you ssh in with vagrant ssh, you can run 
`chmod 777 /srv/www/default/dashboard/cache`

It will either do its job or return an error if the cache directory is not found.

**Comment by eno812** [comment]
Thanks for the clear explanation. I've executed that command and it looks like it's ok as no error has been returned.

**Comment by eno812** [comment]
It's now working! Thanks for all your help and patience.

**Comment by topdown** [comment]
Anytime

**Comment by topdown** [comment]
I'm going to close this. Feel free to open a new ticket if you have any more issues or questions.
Thanks
