### ISSUE TITLE
domains not appearing in the dasboard

### ISSUE THREAD

**Issue by dsgnr** [topdown/VVV-Dashboard#37]
Hello,

I am fairly new to using Vagrant. I have a strange issue with the dashboard where by the domain names, links and WP version number don't seem to appear on my custom domain names.

I made sure they were added to the vvv-hosts file but I just get N/A under sites and version number.

It's not essential I guess but just would be nice to get it to work :)

I'm not really sure how to trouble shoot this so thought I'd ask here. 

Thanks!

**Comment by topdown** [comment]
What version of VVV Dashboard are you using? Make sure its 0.1.7
How are you creating this sites "custom domain names"?

**Comment by dsgnr** [comment]
Hello, I am definitely using 0.1.7.

I'm making new domains by creating a new nginx host file and then either restarting nginx or a provision.

**Comment by topdown** [comment]
There are a couple things that are missing when creating custom sites this way.
VVV Dashboard relies heavily on WPCLI for a lot of its data and tools.
So you have to have the wp-cli.yml file
Go to your VVV/www/your_site folder 
Create a file named  `wp-cli.yml`
in it put `path: htdocs`
No new lines or trailing white space.

But you will have other issue with Vagrant also because your init script for those sites will not have all of the info that vagrant uses to provision each site.

I have a comment here that explains how to fix it or verify that the init script is correct.
https://github.com/topdown/VVV-Dashboard/issues/35#issuecomment-223991586

**Comment by ntillman-tcu** [comment]
having same issue. Read your comment on [#35](https://github.com/topdown/VVV-Dashboard/issues/35#issuecomment-223991586) but don's see the vvv-init.sh for the site i am creating

**Comment by topdown** [comment]
@ntillman-tcu thats the problem. You have to create it. Without it you will not only miss features for that site in VVV Dashboard but also VVV itself.

**Comment by ntillman-tcu** [comment]
I installed [Variable vvv](https://github.com/bradp/vv#os-x-installation) to create my new sites which seemed to resolved issues. It automates the process and creates the necessary files for WPCLI and the other settings the Dashboard depends on for displaying the sites. Thanks again for your help and a great asset to better organize my projects.
